<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Language" content="en_US" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Everything you wanted to know about handling errors and exceptions when writing asynchronous code.">
  <title>Futures and Error Handling | Dart</title>

  <!-- Favicon / Touch Icons -->
  <link rel="icon" sizes="64x64" href="/assets/shared/dart/icon/64.png">
  <link href="/assets/touch-icon-iphone-a46c306c4fbfae0b28d63f512b01d7cb2ccf1e4ca9d7f3aab15ba1170beed4a0.png" rel="apple-touch-icon">
  <link href="/assets/touch-icon-ipad-d0181720760b3912858b6d40da1d5586b1e92c7c8656a485ea41005674401e6b.png" rel="apple-touch-icon" sizes="76x76">
  <link href="/assets/touch-icon-iphone-retina-3d9821a631425376ac6203dea3c23c1940ab7b5c506a25406662fab76cee2e0b.png" rel="apple-touch-icon" sizes="120x120">
  <link href="/assets/touch-icon-ipad-retina-b9715401952522f1daee2b4a4064a1bbfb5ffab78d0a47a7226dc87444d51c32.png" rel="apple-touch-icon" sizes="152x152">

  <!-- Twitter Card -->
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@dart_lang" />
  <meta name="twitter:title" content="Futures and Error Handling" />
  <meta name="twitter:description" content="Everything you wanted to know about handling errors and exceptions when writing asynchronous code." />

  <!-- Open Graph -->
  <meta property="og:title" content="Futures and Error Handling" />
  <meta property="og:description" content="Everything you wanted to know about handling errors and exceptions when writing asynchronous code." />
  <meta property="og:url" content="https://www.dartlang.org/guides/libraries/futures-error-handling" />
  <meta property="og:image" content="https://www.dartlang.org/assets/shared/dart-logo-for-shares.png?2" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" integrity="sha256-EULh7n7c0RZiOHiikIAEzXBQ0AXvb71Ul6a85V4AuTc=" crossorigin="anonymous" href="/assets/main-1142e1ee7edcd116623878a2908004cd7050d005ef6fbd5497a6bce55e00b937.css">
  <script src="/assets/main-8306ad9c5a7b0d639cab54fda750f6ae0b3fb8f964457c69a7ef962a0cc52902.js" integrity="sha256-gwatnFp7DWOcq1T9p1D2rgs/uPlkRXxpp++WKgzFKQI=" crossorigin="anonymous" type="text/javascript"></script>
  <script>

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-26406144-4', 'auto');
ga('send', 'pageview');

</script>


</head>

  <body class="default obsolete">
    <header id="page-header">
  <nav id="mainnav">
  <div id="menu-toggle"><i class="icon icon-menu"></i></div>
  <a href="/" class="brand" title="Dart">
    <img src="/assets/shared/dart/logo+text/horizontal/default-363c9c133ffb7780463d3d638632b64cc8221d74d93cd1002fb1efbbe9983bc9.svg" alt="Dart">
  </a>
  <ul>
    <li class="mainnav__get-started"><a href="/guides/get-started"><span>入门</span></a></li>
    <li><a href="/guides/language">语言</a></li>
    <li><a href="/guides/libraries">库</a></li>
    <li><a href="/tools">工具</a></li>
    
    
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dart 2</a>
      <ul class="dropdown-menu">
        

<li><a href="https://v1-dartlang-org.firebaseapp.com/guides/libraries/futures-error-handling" class="dropdown-item no-automatic-external">1.24.3&nbsp;&nbsp;(archive)</a></li><li><a class="active dropdown-item">2.2.0&nbsp;&nbsp;(stable)</a></li>

        <li role="separator" class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="/dart-2#migration">迁移指南</a></li>
      </ul>
    </li>
    
    <li class="searchfield">
      <form class="navbar-search" action="/search" id="cse-search-box">
        <input type="hidden" name="cx" value="011220921317074318178:_yy-tmb5t_i">
        <input type="hidden" name="ie" value="UTF-8">
        <input type="hidden" name="hl" value="en">
        <input type="search" name="q" id="q" autocomplete="off" placeholder="Search">
        <button type="submit"><i class="icon icon-search"></i></button>
      </form>
    </li>
  </ul>
</nav>

  
  <div class="alert alert-warning">
    <h4 class="text-center">
      Some of the content of this page might be out of date.
    </h4>
  </div>
  
</header>

    <main id="page-content">
      <div id="sidenav" class="">
  <div class="content">
    <a href="/" class="brand" title="Dart">
      <img src="/assets/shared/dart/logo+text/horizontal/default-363c9c133ffb7780463d3d638632b64cc8221d74d93cd1002fb1efbbe9983bc9.svg" alt="Dart">
    </a>

    <div class="sidenav__search">
      <p>
        <a href="/search">Search <i class="icon icon-search"></i></a>
      </p>
    </div>

    <ul>
      <li>
        <a class="btn btn-light" href="/guides/get-started">入门</a>
      </li>
    </ul>
    <h4 ><a href="/guides/language" title="语言">语言</a></h4>
  <ul><li >
          <a href="/guides/language/language-tour" title="概览">概览</a>
        </li>
        
        <li >
          <a href="/guides/language/effective-dart" title="Effective Dart">Effective Dart</a>
          <i class="icon icon-arrow"></i>
          <ul><li >
                <a href="/guides/language/effective-dart/style" title="风格">风格</a>
              </li><li >
                <a href="/guides/language/effective-dart/documentation" title="文档">文档</a>
              </li><li >
                <a href="/guides/language/effective-dart/usage" title="使用">使用</a>
              </li><li >
                <a href="/guides/language/effective-dart/design" title="设计">设计</a>
              </li>
          </ul><li >
          <a href="/samples" title="示例代码">示例代码</a>
        </li>
  </ul><h4 ><a href="/guides/libraries" title="库">库</a></h4>
  <ul><li >
          <a href="/guides/libraries/library-tour" title="概览">概览</a>
        </li>
  </ul><h4 ><a href="/guides/platforms" title="平台">平台</a></h4>
  <ul><li >
          <a href="https://flutterchina.club" title="移动端 (Flutter中文网)">移动端 (Flutter中文网)</a>
        </li><li >
          <a href="https://webdev.dartlang.org" title="Web">Web</a>
        </li><li >
          <a href="/server" title="服务器">服务器</a>
        </li>
  </ul><h4 ><a href="/guides/testing" title="测试">测试</a></h4>
  <ul>
  </ul><h4 >资源</h4>
  <ul><li >
          <a href="/install" title="安装">安装</a>
        </li><li >
          <a href="/codelabs" title="Codelab">Codelab</a>
        </li><li >
          <a href="/tutorials" title="学习指南">学习指南</a>
        </li><li >
          <a href="/tools" title="工具">工具</a>
        </li><li >
          <a href="/community" title="社区支持">社区支持</a>
        </li>
  </ul>
  </div>
</div>

      
<div id="toc">
  <div class="content">
    <header class="h4 text-uppercase">
      目录
      <a title="Back to top" class="back-to-top float-right mr-3">
        <i class="fas fa-angle-up"></i>
      </a>
    </header>
    <ul class="section-nav">
<li class="toc-entry toc-h2"><a href="#async-await-and-exceptions">Async, await, and exceptions</a></li>
<li class="toc-entry toc-h2"><a href="#the-future-api-and-callbacks">The Future API and callbacks</a></li>
<li class="toc-entry toc-h2"><a href="#examples-of-using-then-with-catcherror">Examples of using then() with catchError()</a>
<ul>
<li class="toc-entry toc-h3"><a href="#catcherror-as-a-comprehensive-error-handler">catchError() as a comprehensive error handler</a></li>
<li class="toc-entry toc-h3"><a href="#error-handling-within-then">Error handling within then()</a></li>
<li class="toc-entry toc-h3"><a href="#errors-in-the-middle-of-a-long-chain">Errors in the middle of a long chain</a></li>
<li class="toc-entry toc-h3"><a href="#handling-specific-errors">Handling specific errors</a></li>
</ul>
</li>
<li class="toc-entry toc-h2"><a href="#async-try-catch-finally-using-whencomplete">Async try-catch-finally using whenComplete()</a>
<ul>
<li class="toc-entry toc-h3"><a href="#completing-the-future-returned-by-whencomplete">Completing the Future returned by whenComplete()</a></li>
<li class="toc-entry toc-h3"><a href="#errors-originating-within-whencomplete">Errors originating within whenComplete()</a></li>
</ul>
</li>
<li class="toc-entry toc-h2"><a href="#potential-problem-failing-to-register-error-handlers-early">Potential problem: failing to register error handlers early</a></li>
<li class="toc-entry toc-h2"><a href="#potential-problem-accidentally-mixing-synchronous-and-asynchronous-errors">Potential problem: accidentally mixing synchronous and asynchronous errors</a>
<ul>
<li class="toc-entry toc-h3"><a href="#solution-using-futuresync-to-wrap-your-code">Solution: Using Future.sync() to wrap your code</a></li>
</ul>
</li>
<li class="toc-entry toc-h2"><a href="#more-information">More information</a></li>
</ul>
  </div>
</div>


      <article>
        <div class="content">
           <div class="banner alert alert-info">
  <p class="banner__text">
    
    
    Dart 2.2 现发布，更高的本地代码执行及 Set 字面量的支持。
    <a href="https://medium.com/dartlang/announcing-dart-2-2-faster-native-code-support-for-set-literals-7e2ab19cc86d">了解更多。</a>
  </p>
</div>
 
          

          <div>
            <div id="page-github-links" class="btn-group" aria-label="Page GitHub links" role="group">
  <a href="https://github.com/dartchina/site-www-cn/tree/src_zh_CN/src_zh_CN/_guides/libraries/futures-error-handling.md" class="btn no-automatic-external" title="View page source" target="_blank" rel="noopener">
    <i class="fas fa-file-alt fa-sm"></i>
  </a>
  <a href="https://github.com/dartchina/site-www-cn/issues/new?title='Futures and Error Handling' page issue&body=
Page URL: https://www.dartlang.org/guides/libraries/futures-error-handling%0D%0A
Page source: https://github.com/dartchina/site-www-cn/tree/src_zh_CN/src_zh_CN/_guides/libraries/futures-error-handling.md%0D%0A
%0D%0A
<!-- ADD YOUR DESCRIPTION OF THE PAGE ISSUE HERE: -->" class="btn no-automatic-external" title="Report a issue with this page"
    target="_blank" rel="noopener">
    <i class="fas fa-bug fa-sm"></i>
  </a>
</div>

            <h1>Futures and Error Handling</h1>
          </div>
          <p>This guide describes how to handle errors when writing asynchronous code.
You can write asynchronous code in two ways:</p>

<ul>
  <li>Using <code class="highlighter-rouge">async</code> functions and <code class="highlighter-rouge">await</code> expressions, which use Futures behind
the scenes.</li>
  <li>Using the <a href="https://api.dartlang.org/stable/dart-async/dart-async-library.html">Future API</a>
directly.</li>
</ul>

<aside class="alert alert-info">
  <p><strong>Note:</strong>
If you are unfamiliar with the general concepts behind Futures, first read
<a href="/tutorials/language/futures">Asynchronous Programming: Futures.</a></p>
</aside>

<p>Why would you use the Future API instead of <code class="highlighter-rouge">async</code> and <code class="highlighter-rouge">await</code>? When you
need more control than you can get from <code class="highlighter-rouge">async</code> and <code class="highlighter-rouge">await</code>. For example,
say you want something to happen when a Future completes, but you also want
to immediately continue what you’re doing. If you use <code class="highlighter-rouge">await</code>, activity
suspends until the Future completes. With the Future API,
you can register a callback and continue.</p>

<hr>

<h2 id="async-await-and-exceptions">
<a id="async-await-and-exceptions" class="anchor" href="#async-await-and-exceptions" aria-hidden="true"><span class="octicon octicon-link"></span></a>Async, await, and exceptions</h2>

<p>Use  <a href="/guides/language/language-tour#exceptions">exception
handling</a>—<code class="highlighter-rouge">try</code>, <code class="highlighter-rouge">catch</code>,
and <code class="highlighter-rouge">finally</code>—to handle errors in code that uses async functions
and await expressions. For example:</p>

<pre class="prettyprint lang-dart">Future main() async {
  var dir = new Directory('/tmp');

  <span class="highlight">try</span> {
    var dirList = dir.list();
    await for (FileSystemEntity f in dirList) {
      if (f is File) {
        print('Found file ${f.path}');
      } else if (f is Directory) {
        print('Found dir ${f.path}');
      }
    }
  } <span class="highlight">catch</span> (e) {
    print(e.toString());
  }
}</pre>

<p>The rest of this guide addresses handling errors when using the Future API.</p>

<h2 id="the-future-api-and-callbacks">
<a id="the-future-api-and-callbacks" class="anchor" href="#the-future-api-and-callbacks" aria-hidden="true"><span class="octicon octicon-link"></span></a>The Future API and callbacks</h2>

<p>Functions that use the Future API register callbacks that handle
the value (or the error) that completes a Future. For example:</p>

<pre class="prettyprint lang-dart">myFunc().then(processValue)
        .catchError(handleError);</pre>

<p>The registered callbacks fire based on the following rules: <code class="highlighter-rouge">then()</code>’s
callback fires if it is invoked on a Future that completes with a value;
<code class="highlighter-rouge">catchError()</code>’s callback fires if it is invoked on a Future that completes
with an error.</p>

<p>In the example above, if <code class="highlighter-rouge">myFunc()</code>’s Future completes with a value,
<code class="highlighter-rouge">then()</code>’s callback fires. If no new error is produced within <code class="highlighter-rouge">then()</code>,
<code class="highlighter-rouge">catchError()</code>’s callback does not fire. On the other hand, if <code class="highlighter-rouge">myFunc()</code>
completes with an error, <code class="highlighter-rouge">then()</code>’s callback does not fire, and
<code class="highlighter-rouge">catchError()</code>’s callback does.</p>

<h2 id="examples-of-using-then-with-catcherror">
<a id="examples-of-using-then-with-catcherror" class="anchor" href="#examples-of-using-then-with-catcherror" aria-hidden="true"><span class="octicon octicon-link"></span></a>Examples of using then() with catchError()</h2>

<p>Chained <code class="highlighter-rouge">then()</code> and <code class="highlighter-rouge">catchError()</code> invocations are a common pattern when
dealing with Futures, and can be thought of as the rough equivalent of
try-catch blocks.</p>

<p>The next few sections give examples of this pattern.</p>

<h3 id="catcherror-as-a-comprehensive-error-handler">
<a id="catcherror-as-a-comprehensive-error-handler" class="anchor" href="#catcherror-as-a-comprehensive-error-handler" aria-hidden="true"><span class="octicon octicon-link"></span></a>catchError() as a comprehensive error handler</h3>

<p>The following example deals with throwing an exception from within <code class="highlighter-rouge">then()</code>’s
callback and demonstrates <code class="highlighter-rouge">catchError()</code>’s versatility as an error handler:</p>

<pre class="prettyprint lang-dart">myFunc()
  .then((value) {
    doSomethingWith(value);
    ...
    throw("some arbitrary error");
  })
  .catchError(handleError);</pre>

<p>If <code class="highlighter-rouge">myFunc()</code>’s Future completes with a value, <code class="highlighter-rouge">then()</code>’s callback fires. If
code within <code class="highlighter-rouge">then()</code>’s callback throws (as it does in the example above),
<code class="highlighter-rouge">then()</code>’s Future completes with an error. That error is handled by
<code class="highlighter-rouge">catchError()</code>.</p>

<p>If <code class="highlighter-rouge">myFunc()</code>’s Future completes with an error, <code class="highlighter-rouge">then()</code>’s Future completes
with that error. The error is also handled by <code class="highlighter-rouge">catchError()</code>.</p>

<p>Regardless of whether the error originated within <code class="highlighter-rouge">myFunc()</code> or within
<code class="highlighter-rouge">then()</code>, <code class="highlighter-rouge">catchError()</code> successfully handles it.</p>

<h3 id="error-handling-within-then">
<a id="error-handling-within-then" class="anchor" href="#error-handling-within-then" aria-hidden="true"><span class="octicon octicon-link"></span></a>Error handling within then()</h3>

<p>For more granular error handling, you can register a second (<code class="highlighter-rouge">onError</code>)
callback within <code class="highlighter-rouge">then()</code> to handle Futures completed with errors. Here is
<code class="highlighter-rouge">then()</code>’s signature:</p>

<pre class="prettyprint lang-dart">abstract Future then(onValue(T value), {onError(AsyncError asyncError)})</pre>

<p>Register the optional onError callback only if you want to differentiate
between an error forwarded <em>to</em> <code class="highlighter-rouge">then()</code>, and an error generated <em>within</em>
<code class="highlighter-rouge">then()</code>:</p>

<pre class="prettyprint lang-dart">funcThatThrows()
  .then(successCallback, onError: (e) {
    handleError(e);          // Original error.
    anotherFuncThatThrows(); // Oops, new error.
  })
  .catchError(handleError);  // Error from within then() handled.</pre>

<p>In the example above, <code class="highlighter-rouge">funcThatThrows()</code>’s Future’s error is handled with the
<code class="highlighter-rouge">onError</code> callback; <code class="highlighter-rouge">anotherFuncThatThrows()</code> causes <code class="highlighter-rouge">then()</code>’s Future to
complete with an error; this error is handled by <code class="highlighter-rouge">catchError()</code>.</p>

<p>In general, implementing two different error handling strategies is not
recommended: register a second callback only if there is a compelling reason
to catch the error within <code class="highlighter-rouge">then()</code>.</p>

<h3 id="errors-in-the-middle-of-a-long-chain">
<a id="errors-in-the-middle-of-a-long-chain" class="anchor" href="#errors-in-the-middle-of-a-long-chain" aria-hidden="true"><span class="octicon octicon-link"></span></a>Errors in the middle of a long chain</h3>

<p>It is common to have a succession of <code class="highlighter-rouge">then()</code> calls, and catch errors
generated from any part of the chain using <code class="highlighter-rouge">catchError()</code>:</p>

<pre class="prettyprint lang-dart">Future&lt;String&gt; one()   =&gt; new Future.value("from one");
Future&lt;String&gt; two()   =&gt; new Future.error("error from two");
Future&lt;String&gt; three() =&gt; new Future.value("from three");
Future&lt;String&gt; four()  =&gt; new Future.value("from four");

void main() {
  one()                                   // Future completes with "from one".
    .then((_) =&gt; two())                   // Future completes with two()'s error.
    .then((_) =&gt; three())                 // Future completes with two()'s error.
    .then((_) =&gt; four())                  // Future completes with two()'s error.
    .then((value) =&gt; processValue(value)) // Future completes with two()'s error.
    .catchError((e) {
      print("Got error: ${e.error}");     // Finally, callback fires.
      return 42;                          // Future completes with 42.
    })
    .then((value) {
      print("The value is $value");
    });
}

// Output of this program:
//   Got error: error from two
//   The value is 42</pre>

<p>In the code above, <code class="highlighter-rouge">one()</code>’s Future completes with a value, but <code class="highlighter-rouge">two()</code>’s
Future completes with an error. When <code class="highlighter-rouge">then()</code> is invoked on a Future that
completes with an error, <code class="highlighter-rouge">then()</code>’s callback does not fire. Instead,
<code class="highlighter-rouge">then()</code>’s Future completes with the error of its receiver. In our example,
this means that after <code class="highlighter-rouge">two()</code> is called, the Future returned by every
subsequent <code class="highlighter-rouge">then()</code>completes with <code class="highlighter-rouge">two()</code>’s error. That error is finally
handled within <code class="highlighter-rouge">catchError()</code>.</p>

<h3 id="handling-specific-errors">
<a id="handling-specific-errors" class="anchor" href="#handling-specific-errors" aria-hidden="true"><span class="octicon octicon-link"></span></a>Handling specific errors</h3>

<p>What if we want to catch a specific error? Or catch more than one error?</p>

<p><code class="highlighter-rouge">catchError()</code> takes an optional named argument, <code class="highlighter-rouge">test</code>, that
allows us to query the kind of error thrown.</p>

<pre class="prettyprint lang-dart">abstract Future catchError(onError(AsyncError asyncError), {bool test(Object error)})</pre>

<p>Consider <code class="highlighter-rouge">handleAuthResponse(params)</code>, a function that authenticates a user
based on the params provided, and redirects the user to an appropriate URL.
Given the complex workflow, <code class="highlighter-rouge">handleAuthResponse()</code> could generate various
errors and exceptions, and you should handle them differently. Here’s
how you can use <code class="highlighter-rouge">test</code> to do that:</p>

<pre class="prettyprint lang-dart">void main() {
  handleAuthResponse({'username': 'johncage', 'age': 92})
    .then((_) =&gt; ...)
    .catchError(handleFormatException,
                test: (e) =&gt; e is FormatException)
    .catchError(handleAuthorizationException,
                test: (e) =&gt; e is AuthorizationException);
}</pre>

<h2 id="async-try-catch-finally-using-whencomplete">
<a id="async-try-catch-finally-using-whencomplete" class="anchor" href="#async-try-catch-finally-using-whencomplete" aria-hidden="true"><span class="octicon octicon-link"></span></a>Async try-catch-finally using whenComplete()</h2>

<p>If <code class="highlighter-rouge">then().catchError()</code> mirrors a try-catch, <code class="highlighter-rouge">whenComplete()</code> is the
equivalent of ‘finally’. The callback registered within <code class="highlighter-rouge">whenComplete()</code> is
called when <code class="highlighter-rouge">whenComplete()</code>’s receiver completes, whether it does so with a
value or with an error:</p>

<pre class="prettyprint lang-dart">var server = connectToServer();
server.post(myUrl, fields: {"name": "john", "profession": "juggler"})
      .then(handleResponse)
      .catchError(handleError)
      .whenComplete(server.close);</pre>

<p>We want to call <code class="highlighter-rouge">server.close</code> regardless of whether <code class="highlighter-rouge">server.post()</code> produces
a valid response, or an error. We ensure this happens by placing it inside
<code class="highlighter-rouge">whenComplete()</code>.</p>

<h3 id="completing-the-future-returned-by-whencomplete">
<a id="completing-the-future-returned-by-whencomplete" class="anchor" href="#completing-the-future-returned-by-whencomplete" aria-hidden="true"><span class="octicon octicon-link"></span></a>Completing the Future returned by whenComplete()</h3>

<p>If no error is emitted from within <code class="highlighter-rouge">whenComplete()</code>, its Future completes
the same way as the Future that <code class="highlighter-rouge">whenComplete()</code> is invoked on. This is
easiest to understand through examples.</p>

<p>In the code below, <code class="highlighter-rouge">then()</code>’s Future completes with an error, so
<code class="highlighter-rouge">whenComplete()</code>’s Future also completes with that error.</p>

<pre class="prettyprint lang-dart">void main() {
  funcThatThrows()
    .then((_) =&gt; print("won't reach here"))    // Future completes with an error.
    .whenComplete(() =&gt; print('reaches here')) // Future completes with the same error.
    .then((_) =&gt; print("won't reach here"))    // Future completes with the same error.
    .catchError(handleError);                  // Error is handled here.
}</pre>

<p>In the code below, <code class="highlighter-rouge">then()</code>’s Future completes with an error, which is now
handled by <code class="highlighter-rouge">catchError()</code>.  Because <code class="highlighter-rouge">catchError()</code>’s Future completes with
<code class="highlighter-rouge">someObject</code>, <code class="highlighter-rouge">whenComplete()</code>’s Future completes with that same object.</p>

<pre class="prettyprint lang-dart">void main() {
  funcThatThrows()
    .then((_) =&gt; ...)         // Future completes with an error.
    .catchError((e) {
      handleError(e);
      printErrorMessage();
      return someObject;
    })                                   // Future completes with someObject.
    .whenComplete(() =&gt; print("Done!")); // Future completes with someObject.
}</pre>

<h3 id="errors-originating-within-whencomplete">
<a id="errors-originating-within-whencomplete" class="anchor" href="#errors-originating-within-whencomplete" aria-hidden="true"><span class="octicon octicon-link"></span></a>Errors originating within whenComplete()</h3>
<p>If <code class="highlighter-rouge">whenComplete()</code>’s callback throws an error, then <code class="highlighter-rouge">whenComplete()</code>’s Future
completes with that error:</p>

<pre class="prettyprint lang-dart">void main() {
  funcThatThrows()
    .catchError(handleError)               // Future completes with a value.
    .whenComplete(() =&gt; throw "new error") // Future completes with an error.
    .catchError(handleError);              // Error is handled.
}</pre>

<h2 id="potential-problem-failing-to-register-error-handlers-early">
<a id="potential-problem-failing-to-register-error-handlers-early" class="anchor" href="#potential-problem-failing-to-register-error-handlers-early" aria-hidden="true"><span class="octicon octicon-link"></span></a>Potential problem: failing to register error handlers early</h2>

<p>It is crucial that error handlers are installed before a Future completes:
this avoids scenarios where a Future completes with an error, the error
handler is not yet attached, and the error accidentally propagates. Consider
this code:</p>

<pre class="prettyprint lang-dart">void main() {
  Future future = funcThatThrows();

  // BAD. Too late to handle funcThatThrows() exception.
  new Future.delayed(const Duration(milliseconds: 500), () {
    future.then(...)
          .catchError(...);
  });
}</pre>

<p>In the code above, <code class="highlighter-rouge">catchError()</code> is not registered until half a second after
<code class="highlighter-rouge">funcThatThrows()</code> is called, and the error goes unhandled.</p>

<p>The problem goes away if <code class="highlighter-rouge">funcThatThrows()</code> is called within the
<code class="highlighter-rouge">Future.delayed()</code> callback:</p>

<pre class="prettyprint lang-dart">void main() {
  new Future.delayed(const Duration(milliseconds: 500), () {
    funcThatThrows().then(processValue)
                    .catchError(handleError)); // We get here.
  });
}</pre>

<h2 id="potential-problem-accidentally-mixing-synchronous-and-asynchronous-errors">
<a id="potential-problem-accidentally-mixing-synchronous-and-asynchronous-errors" class="anchor" href="#potential-problem-accidentally-mixing-synchronous-and-asynchronous-errors" aria-hidden="true"><span class="octicon octicon-link"></span></a>Potential problem: accidentally mixing synchronous and asynchronous errors</h2>

<p>Functions that return Futures should almost always emit their errors in the
future. Since we do not want the caller of such functions to have to
implement multiple error-handling scenarios, we want to prevent any synchronous
errors from leaking out. Consider this code:</p>

<pre class="prettyprint lang-dart">Future&lt;int&gt; parseAndRead(data) {
  var filename = obtainFileName(data);         // Could throw.
  File file = new File(filename);
  return file.readAsString().then((contents) {
    return parseFileData(contents);            // Could throw.
  });
}</pre>

<p>Two functions in that code could potentially throw synchronously:
<code class="highlighter-rouge">obtainFileName()</code> and <code class="highlighter-rouge">parseFileData()</code>. Because <code class="highlighter-rouge">parseFileData()</code> executes
inside a <code class="highlighter-rouge">then()</code> callback, its error does not leak out of the function.
Instead, <code class="highlighter-rouge">then()</code>’s Future completes with <code class="highlighter-rouge">parseFileData()</code>’s error, the error
eventually completes <code class="highlighter-rouge">parseAndRead()</code>’s Future, and the error can be
successfully handled by <code class="highlighter-rouge">catchError()</code>.</p>

<p>But <code class="highlighter-rouge">obtainFileName()</code> is not called within a <code class="highlighter-rouge">then()</code> callback; if <em>it</em>
throws, a synchronous error propagates:</p>

<pre class="prettyprint lang-dart">void main() {
  parseAndRead(data).catchError((e) {
    print("inside catchError");
    print(e.error);
  });
}

// Program Output:
//   Unhandled exception:
//   &lt;error from obtainFileName&gt;
//   ...</pre>

<p>Because using <code class="highlighter-rouge">catchError()</code> does not capture the error, a client of
<code class="highlighter-rouge">parseAndRead()</code> would implement a separate error-handling strategy for this
error.</p>

<h3 id="solution-using-futuresync-to-wrap-your-code">
<a id="solution-using-futuresync-to-wrap-your-code" class="anchor" href="#solution-using-futuresync-to-wrap-your-code" aria-hidden="true"><span class="octicon octicon-link"></span></a>Solution: Using Future.sync() to wrap your code</h3>

<p>A common pattern for ensuring that no synchronous error is accidentally
thrown from a function is to wrap the function body inside a <code class="highlighter-rouge">new Future.sync()</code>
callback:</p>

<pre class="prettyprint lang-dart">Future&lt;int&gt; parseAndRead(data) {
  return new Future.sync(() {
    var filename = obtainFileName(data);         // Could throw.
    File file = new File(filename);
    return file.readAsString().then((contents) {
      return parseFileData(contents);            // Could throw.
    });
  });
}</pre>

<p>If the callback returns a non-Future value, <code class="highlighter-rouge">Future.sync()</code>’s Future completes
with that value. If the callback throws (as it does in the example
above), the Future completes with an error. If the callback itself returns a
Future, the value or the error of that Future completes <code class="highlighter-rouge">Future.sync()</code>’s
Future.</p>

<p>With code wrapped within <code class="highlighter-rouge">Future.sync()</code>, <code class="highlighter-rouge">catchError()</code> can handle all errors:</p>

<pre class="prettyprint lang-dart">void main() {
  parseAndRead(data).catchError((e) {
    print("inside catchError");
    print(e.error);
  });
}

// Program Output:
//   inside catchError
//   &lt;error from obtainFileName&gt;</pre>

<p><code class="highlighter-rouge">Future.sync()</code> makes your code resilient against uncaught exceptions. If your
function has a lot of code packed into it, chances are that you could be doing
something dangerous without realizing it:</p>

<pre class="prettyprint lang-dart">Future fragileFunc() {
  return new Future.sync(() {
    var x = someFunc();     // Unexpectedly throws in some rare cases.
    var y = 10 / x;         // x should not equal 0.
    ...
  });
}</pre>

<p><code class="highlighter-rouge">Future.sync()</code> not only allows you to handle errors you know might occur, but
also prevents errors from <em>accidentally</em> leaking out of your function.</p>

<h2 id="more-information">
<a id="more-information" class="anchor" href="#more-information" aria-hidden="true"><span class="octicon octicon-link"></span></a>More information</h2>

<p>The following docs have more information on Futures:</p>

<ul>
  <li>
<a href="https://webdev.dartlang.org/articles/performance/event-loop">The Event Loop and Dart</a>,
an article that describes how to schedule tasks using Futures</li>
  <li><a href="https://api.dartlang.org/stable/dart-async/Future-class.html">Future API reference</a></li>
</ul>


          

        </div>
      </article>
    </main>
    <footer id="page-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-3">
        <div class="content">
          <div class="brand">
            <img src="/assets/shared/dart/logo+text/horizontal/mono-004b4974b3112e2d9136b1c457037dfd9fe54e2e69e850d777891e5c2a57a78d.svg" alt="Dart logo" class="brand"/>
          </div>
          <h4><a href="/terms">Terms</a> | <a href="https://policies.google.com/privacy">Privacy</a></h4>
          <style>.menu .material-icons { font-size: 14px; }</style><ul class="menu">
            <li>Site&nbsp;<a href="http://creativecommons.org/licenses/by/3.0/" class="no-automatic-external">CC&nbsp;BY&nbsp;3.0</a></li>
            <li>
              <a href="https://github.com/dartchina/site-www-cn"
                 title="This site's source is on GitHub."
                 class="no-automatic-external"><i class="fab fa-github fa-sm"></i></a>
              &nbsp;
              <a href="https://github.com/dartchina/site-www-cn/issues"
                 title="File an issue about this site."
                 class="no-automatic-external"><i class="fas fa-bug fa-sm"></i></a>
              &nbsp;
              <a 
                 title="Site built on 2019/04/10 17:20 PDT"
                 
                 class="no-automatic-external"><i class="material-icons">build</i></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-4 col-lg-3">
        <div class="content">
          <h4>技术</h4>
          <ul>
            <li><a href="https://flutterchina.club">Dart 移动开发 (Flutter)</a></li>
            <li><a href="https://webdev.dartlang.org">Dart web 开发</a></li>
            <li><a href="/server">Dart 服务器开发</a></li>
            <li><a href="https://dart-lang.github.io/observatory/">Observatory 工具</a></li>
            <li><a href="/guides/libraries">Dart 库</a></li>
            <li><a href="/guides/language">Dart 编程语言</a></li>
          </ul>
        </div>
      </div>

      <div class="col-md-4 col-lg-3">
        <div class="content">
          <h4>资源</h4>
          <ul>
            <li><a href="https://api.dartlang.org/stable">API 参考</a></li>
            <li><a href="https://dartpad.cn">DartPad</a></li>
            <li><a href="https://pub.dartlang.org">Dart packages</a></li>
            <li><a href="https://news.dartlang.org">Dart 新闻</a></li>
            <li><a href="https://github.com/dart-lang/sdk/issues">Dart bugs 和 <br> 新需求</a></li>
          </ul>
        </div>
      </div>

      <div class="col-md-4 col-lg-3">
        <div class="content">
          <h4>社区</h4>
          <ul>
            <li><a href="/community">支持和邮件列表</a></li>
            <li><a href="/community/who-uses-dart">谁在用Dart</a></li>
            <li><a href="http://stackoverflow.com/questions/tagged/dart">Stack Overflow</a></li>
            <li><a href="https://gitter.im/dart-lang/home">Gitter 聊天室</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

  </body>
</html>
